import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '@/store/provider';
import { SocketProvider } from '../context/SocketContext';
import BgAudioPlayer from '@/components/common/BgAudioPlayer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '말랑연구소',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // redux 적용
    <html lang="en" className={inter.className}>
      <body className="text-black">
        <Providers>
          <SocketProvider>{children}</SocketProvider>
        </Providers>
      </body>
    </html>
  );
}
