'use client'

import './globals.css';
import { Inter } from 'next/font/google';
import { Providers } from '@/store/provider';
import { SocketProvider } from '../context/SocketContext';
import { useEffect } from 'react';
import { RootState } from '@/store/store';
import { useSelector } from 'react-redux';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '말랑연구소',
  description: 'Generated by Next.js',
};

function Check() {
  const guest = useSelector((state: RootState) => state.guest)

  // 새로고침 또는 페이지를 이동할 때
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      e.preventDefault();
      e.returnValue = '';
      console.log(guest.pin, '❤')

      if(guest.pin.trim()){
        // const headers = new Headers()
        // headers.append('Authorization', localStorage.getItem('token'))
        const token = localStorage.getItem('token')
        console.log(token)
        // const data = {
        //   token,
        // }



        navigator.sendBeacon(`https://api.malang-lab.com/game/${guest.pin}/user/out`, token)
      }
    }

    window.addEventListener('beforeunload', handleBeforeUnload)
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    }
  }, [guest])

  return null;
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // redux 적용
    <html lang="en" className={inter.className}>
      <body className="text-black">
        <Providers>
          <Check />
          <SocketProvider>{children}</SocketProvider>
        </Providers>
      </body>
    </html>
  );
}
